name: Notify Teams

on:
  pull_request:
    types: [opened]
    branches:
      - test-new

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Microsoft Teams
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "New Pull Request Created!\nRepository: ${{ github.repository }}\nPR Title: ${{ github.event.pull_request.title }}\nAuthor: ${{ github.event.pull_request.user.login }}\nURL: ${{ github.event.pull_request.html_url }}"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
