name: Notify Teams

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Microsoft Teams
        uses: distributhor/action-ms-teams@v2
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: |
            New Pull Request Created!
            Repository: ${{ github.repository }}
            PR Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            URL: ${{ github.event.pull_request.html_url }}
